---
# ####################################################################################
# This is the main playbook, which is used to call all the roles that will allow the 
# installation of an Oracle Database 12c using an RSP file
# ####################################################################################

- hosts: database
  remote_user: oracle
  tasks:
     # This task is used to load the variables, which are defined outside roles directories
     # The variable called environment is passed as extra-vars parameter when ansible-playbook
     # command is executed
   - name: Loading variables according to the environment you are working on
     include_vars: "{{ item }}"
     with_fileglob:
      - "inventories/{{ environment_chosen }}/group_vars/*.yml"
   - include_role:
       name: os_settings
   - include_role:
       name: install_oracle_db

- hosts: database
  remote_user: oracle
  become: yes
  become_user: root
  tasks:
    # Here we will call the role to create Linux Services for Oracle database
   - include_role:
       name: create_db_service

- hosts: database
  remote_user: oracle
  tasks:
   - name: Stopping the database listener
     command: "{{ oracle_home }}/bin/lsnrctl stop"

   - name: Stopping the database
     command: "{{ oracle_home }}/bin/dbshut {{ oracle_home }}"

   - name: Starting Oracle database listener
     service:
       name: oracledblistener
       state: started

   - name: Starting Oracle database
     service:
       name: oracledb
       state: started
