- hosts: database
  remote_user: oracle
  tasks:
   - name: Loading variables according to the environment you are working on
     include_vars: "{{ item }}"
     with_fileglob:
      - "inventories/{{ environment_chosen }}/group_vars/*.yml"

- hosts: database
  remote_user: oracle
  tasks:
   - name: Stopping the database
     command: "{{ oracle_home }}/bin/dbshut {{ oracle_home }}"

- hosts: database
  remote_user: oracle
  become: yes
  become_user: root
  tasks:
   - name: Starting Oracle database listener
     service:
       name: oracledblistener
       state: started

   - name: Starting Oracle database
     service:
       name: oracledb
       state: started
