---
# tasks file for install_oracle_db

 - name: Creating a staging directory
   file:
     path: "{{ inst_sofware_destiny_dir }}"
     state: directory

 - name: Copying Oracle 12 database installer
   copy:
     src: "{{ inst_software_source_dir }}/{{ inst_db_installer }}"
     dest: "{{ inst_sofware_destiny_dir }}"
     creates: "{{ inst_software_source_dir }}/{{ inst_db_installer }}"

 - name: Unzipping Oracle database installer
   unarchive:
     src: "{{ inst_sofware_destiny_dir }}/{{ inst_db_installer }}"
     dest: "{{ inst_sofware_destiny_dir }}"
     remote_src: yes
     creates: "{{ inst_sofware_destiny_dir }}/runInstaller"

 - name: Creating a directory for templates
   file:
     path: "{{ inst_template_dir }}"
     state: directory

 - name: Creating the response file to install and configure the database
   template:
     src: db_install.rsp
     dest: "{{ inst_template_dir }}"

 - name: Creating the directory to install the databse
   file:
     path: "{{ inst_root_dir }}"
     state: directory
     mode: g+s

 - name: Installing and configuring the database
   command: "{{ inst_sofware_destiny_dir }}/database/runInstaller \
            -responseFile {{ inst_template_dir }}/db_install.rsp -silent -waitforcompletion -showProgress"

 - name: "Executing {{ inst_ora_root_file }}"
   command: "{{ inst_ora_root_file }}"
   become: yes
   become_user: root
   args:
     creates: "{{ inst_ora_tab_file }}"

 - name: Executing runInstaller with executeConfigTools
   command: "{{ inst_sofware_destiny_dir }}/database/runInstaller \
            -executeConfigTools -responseFile {{ inst_template_dir }}/db_install.rsp \
            -silent -waitforcompletion -showProgress"

 - name: Setting environment variables in .bash_profile
   template:
     src: .bash_profile
     dest: "{{ inst_user_home }}"
     mode: '0644'     
